# Generated by Django 5.2.10 on 2026-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_description_alter_film_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image_url',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
    ]
