# Generated by Django 5.2.10 on 2026-02-07 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_star_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='star',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
