# Generated by Django 5.2.10 on 2026-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2),
        ),
    ]
